[package]
name = "nano-9"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
# bevy-inspector-egui = "0.28"
# bevy = { version = "0.13", default-features = false, features = [ "bevy_winit", "bevy_asset", "bevy_render" ] }
# bevy_asset_loader = "0.21"
bevy_ecs_ldtk = { version = "0.11", optional = true }
bevy_mod_scripting = { version = "0.9.0-alpha.7", features = ["lua54", "core_functions"] }
bytemuck = "1.16.3"
thiserror = "1.0.63"
# bevy_pixel_buffer = "0.7.0"
bevy_minibuffer = "0.3.0"
# bevy_minibuffer_inspector = "0.1.0"
serde = "1.0.217"
bevy_ecs_tilemap = "0.15.0"
keyseq = { version = "0.5.0", features = ["bevy"] }
dasp = { version = "0.11.0", features = ["all"] }
# regex = "1.11.1"

[features]
level = [ "dep:bevy_ecs_ldtk" ]

[dev-dependencies]
bevy = "0.15"

[[bin]]
name = "nano-9"
test = false
bench = false

[patch.crates-io]
bevy_minibuffer = { path = "../bevy_minibuffer" }
bevy_mod_scripting = { path = "../bevy_mod_scripting" }
# bevy_pixel_buffer = { path = "../bevy_pixel_buffer" }
