[package]
name = "nano-9"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
# bevy = { version = "0.13", default-features = false, features = [ "bevy_winit", "bevy_asset", "bevy_render" ] }
bevy_asset_loader = "0.20"
bevy_mod_scripting = { version = "0.6.0", features = ["lua54", "lua_script_api"] }
bytemuck = "1.16.3"
thiserror = "1.0.63"
# bevy_pixel_buffer = "0.7.0"

[dev-dependencies]
bevy = "0.13"

[[bin]]
name = "nano-9"
test = false
bench = false

# [patch.crates-io]
# bevy_pixel_buffer = { path = "../bevy_pixel_buffer" }
